# Site settings
title: "Diego's notes"
author: "Diego Lemos"
description: "Writing software that works (and occasionally taking notes)"
url: "https://diegolemos.net"

show_excerpts: true

# Minima theme settings
theme: minima

header_pages:
  - about.md
  - tags.md

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "page"

exclude:
  - CHANGELOG.md
  - Gemfile
  - Gemfile.lock
  - README.md

plugins:
  - jekyll-feed
  - jekyll-sitemap
